name: "Schedule"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  default:
    name: "Generate"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: "Run deno"
        run: |
          deno run --allow-env --allow-net --allow-write .github/scripts/main.ts

      - name: "Configure git"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"

      - name: "Push markdown"
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add ./README.md
            git commit -m 'gen: update snippets list'
            git push origin main
          fi